#Question-1
import sqlite3
conn=sqlite3.connect('test1.db')
''''
conn.execute("CREATE TABLE BOOK (BOOKID INT PRIMARY KEY,TITLEID INT,LOCATION TEXT,GENRE TEXT)")
conn.execute("CREATE TABLE TITLES (TITLEID INT PRIMARY KEY,TITLE TEXT,ISBN TEXT,PUBLISHERID INT,PUBLICATIONYEAR INT)")
conn.execute("CREATE TABLE PUBLISHERS(PUBLISHERID INT PRIMARY KEY,NAME TEXT,STREETADDRESS TEXT,SUITEADDRESS TEXT,ZIPCODEID TEXT)")
conn.execute("CREATE TABLE ZIPCODES(ZIPCODEID INT PRIMARY KEY,CITY TEXT,STATE TEXT,ZIPCODE INT)")
conn.execute("CREATE TABLE AUTHORTITLES(AUTHORTITLEID INT PRIMARY KEY,AUTHORID INT,TITLEID INT)")
conn.execute("CREATE TABLE AUTHORS(AUTHORID INT PRIMARY KEY,FIRSTNAME TEXT,MIDDLENAME TEXT,LASTNAME TEXT)")
'''
'''
#Question-2
conn.execute("INSERT INTO BOOK VALUES(1,2,'LUDHIANA','FICTION')")
conn.execute("INSERT INTO BOOK VALUES(2,3,'BHATINDA','THRILLER')")
conn.execute("INSERT INTO TITLES VALUES(1,'ABC','LUDHIANA',5,2015)")
conn.execute("INSERT INTO TITLES VALUES(2,'kBC','LUDHIANA',8,1915)")
conn.execute("INSERT INTO PUBLISHERS VALUES(1,'VIKU','LUDHIANA','BATHINDA',8765)")
conn.execute("INSERT INTO PUBLISHERS VALUES(2,'BIJU','LUDHIANA','BATHINDA',9765)")
conn.execute("INSERT INTO ZIPCODES VALUES(1,'LUDHIANA','PUNJAB',8765)")
conn.execute("INSERT INTO ZIPCODES VALUES(2,'LUDHIANA','PUNJAB',9765)")
conn.execute("INSERT INTO AUTHORTITLES VALUES(1,2,3)")
conn.execute("INSERT INTO AUTHORTITLES VALUES(2,3,4)")
conn.execute("INSERT INTO AUTHORS VALUES(1,'VIVEK','RAVINDER','MISHRA')")
conn.execute("INSERT INTO AUTHORS VALUES(2,'SACHIN','RAMESH','TENDULKAR')")
'''
'''
#QUESTION-3
print("BEFORE UPDATION RECORDS ARE")
cursor=conn.execute("SELECT * FROM AUTHORS")
for row in cursor:
    print("AUTHOR_ID :",row[0])
    print("FIRST NAME :", row[1])
    print("MIDDLE NAME :", row[2])
    print("LAST NAME :", row[3])

conn.execute("UPDATE AUTHORS SET FIRSTNAME='VIKU' WHERE AUTHORID=1")

print("AFTER UPDATION RECORDS ARE")
cursor=conn.execute("SELECT * FROM AUTHORS")
for row in cursor:
    print("AUTHOR_ID :",row[0])
    print("FIRST NAME :", row[1])
    print("MIDDLE NAME :", row[2])
    print("LAST NAME :", row[3])


conn.commit()
'''